# If you don't set these, they will be inferred from the repo's description on GitHub.

# title: My project title
# description: My description

remote_theme: yaoyao-liu/minimal-light

plugins:
  - jekyll-remote-theme

title: Shanyu Thibaut
description: Hi, I'm a developer, and this is my site
cv_link: assets/resume.pdf
github_link: https://github.com/terminalsin
avatar: ./assets/img/avatar.avif
favicon: ./assets/img/favicon.jpg
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
